import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/contexts/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>{children}</div>{" "}
        </body>
      </html>
    </UserProvider>
  );
}
